### ISSUE TITLE
The installation fails

### ISSUE THREAD

**Issue by WDSB** [rongeb/lgv-cms#3]
When I try to install lgv-cms get the following error messages

Update failed (The .git directory is missing from /var/www/vhosts/com2gay.com/zf2/vendor/rongeb/libraries-for-lgv-cms, see https://getcomposer.org/commit-deps for more information )

Could not scan for classes inside "/var/www/vhosts/com2gay.com/zf2Update failed (The .git directory is missing from /var/www/vhosts/com2gay.com/zf2/vendor/rongeb/libraries-for-lgv -cms, see https://getcomposer.org/commit-deps for more information)

Could not scan for classes inside "/var/www/vhosts/com2gay.com/zf2/vendor/rongeb/dynamiclayout/./Module.php" which does not appear to be a file nor a folder./Module.php "which does not appear to be a file nor a folder

the directory Update failed (The .git directory is missing from /var/www/vhosts/com2gay.com/zf2/vendor/rongeb/libraries-for-lgv-cms, see https://getcomposer.org/commit-deps for more information)

Could not scan for classes inside "/var/www/vhosts/com2gay.com/zf2/vendor/rongeb/dynamiclayout/./Module.php" which does not appear to be a file nor a 

the folder i/vendor/rongeb/dynamiclayout/ s empty

**Comment by rongeb** [comment]
Hi,
Please update the project.
Delete the content in the vendor folder. 
Run composer install.
All the dependencies will be installed.

**Comment by WDSB** [comment]
thanks

However, I now have the problem that not all files are in the config directory :(

files are missing in the config directory :(

LG
Willi

Von: rongeb ***@***.***>
Antworten an: rongeb/lgv-cms ***@***.***>
Datum: Sonntag, 4. Juli 2021 um 22:16
An: rongeb/lgv-cms ***@***.***>
Cc: WDSB ***@***.***>, Author ***@***.***>
Betreff: Re: [rongeb/lgv-cms] The installation fails (#3)


Hi,
Please update the project.
Delete the content in the vendor folder.
Run composer install.
All the dependencies will be installed.

**Comment by WDSB** [comment]
got the problem with the missing files in the config directory solved :)

However, when I call up the page I get the message


--------

A 404 error occurred
Page not found.

The requested controller was unable to dispatch the request.

Controller:
     Sitepublic \ Controller \ SitepublicController

No exception available

--------

Please don't be angry, but if you already publish something on Github then please something that is functiona l;)

Willi

Von: rongeb ***@***.***>
Antworten an: rongeb/lgv-cms ***@***.***>
Datum: Sonntag, 4. Juli 2021 um 22:16
An: rongeb/lgv-cms ***@***.***>
Cc: WDSB ***@***.***>, Author ***@***.***>
Betreff: Re: [rongeb/lgv-cms] The installation fails (#3)


Hi,
Please update the project.
Delete the content in the vendor folder.
Run composer install.
All the dependencies will be installed.

**Comment by rongeb** [comment]
Hi,
I know it is not so easy to install. Few knowledge of Laminas or Zend 2 or 3 could be useful.

Please notice that the information regarding the url have been written in the readme.md.
This is an extract :
"
**urls of the applications You can find the url of the module in their config folder in the module.config.php These are relative url usefull to start :

backoffice login : /backofficeaccess
public web page : /sitepublic/displaypublicpage/your page without phtml extension
extranet login : /siteprivate?myspace=token of your private space (you will find the token in the database)
extranet web page : /siteprivate/displayprivatepage/your page without phtml extension_**
Default login to connect to the back-office ...**
"
If you run your the project locally and you want to display the basic index page provided (just for example purpose) by the project it could be something like this : 
http://localhost/the_folder_where_you_have_installed_the_project/public/sitepublic/displaypublicpage/the_page_you_have_created or nothing if it is the index page

Hope it helps.
